laddu247/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import laddus

urlpatterns = patterns('',

	url(r'^admin/', include(admin.site.urls)),
	
	url(r'^$', 'laddus.views.home', name='home'),
	
	url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'},name='login_Page'),
	url(r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login'),
		      
	url(r'^accounts/profile/$', 'laddus.views.account_profile', name='account_profile'),
	url(r'^user/register$', 'laddus.views.userRegister', name='userRegister'),
	url(r'^user/save$', 'laddus.views.saveUser', name='saveUser'),

	url(r'^user/forgot/password$', 'laddus.views.forgotPasswordView', name='forgotPasswordView'),
	url(r'^user/pswd/send/mail$', 'laddus.views.forgotPassword', name='forgotPassword'),
	url(r'^reset/password/using$', 'laddus.views.resetPasswordUsingKey', name='resetPasswordUsingKey'),
	url(r'^save/new/password$', 'laddus.views.savePswdUsingKey', name='savePswdUsingKey'),
	url(r'^reset/password$', 'laddus.views.resetPassword', name='resetPassword'),
	url(r'^reset/password/save$', 'laddus.views.resetPasswordSave', name='resetPasswordSave'),

	url(r'^home/Submit$', 'laddus.views.homeSubmition', name='homeSubmition'),

	
	url(r'^jobs$', 'laddus.views.jobs', name='jobs'),
	url(r'^jobs/add$', 'laddus.views.addJob', name='newJob'),
	url(r'^job/(?P<id>[-\w]+)/$', 'laddus.views.jobStats', name='jobStats'),
	
	url(r'^job/start/(?P<id>[-\w]+)/$', 'laddus.views.jobStart', name='jobStart'),
	url(r'^job/stop/(?P<id>[-\w]+)/$', 'laddus.views.jobStop', name='jobStop'),
	url(r'^job/remove/(?P<id>[-\w]+)/$', 'laddus.views.jobRemove', name='jobRemove'),
	
	
	#SMS
	url(r'^job/add/smsAlert/(?P<id>[-\w]+)/$', 'laddus.views.jobAddSMSAlert', name='addSMSAlert'),
	url(r'^job/del/smsAlert/(?P<id>[-\w]+)/(?P<phoneNumber>[-\w]+)/$', 'laddus.views.jobDelSMSAlert', name='delSMSAlert'),
	
	# Email
	url(r'^job/add/emailAlert/(?P<id>[-\w]+)/$', 'laddus.views.jobAddEMAlert', name='addEMAlert'),
	url(r'^job/del/emailAlert/(?P<id>[-\w]+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})/$', 'laddus.views.jobDelEMAlert', name='delEMAlert'),
	

)

laddus/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from  django.utils.text import slugify
from datetime import datetime
from alertCeleryJobs import sendSMS, sendEmail

from django.forms import ModelForm
import pymongo

from pymongo import MongoClient
from bson.json_util import dumps

import time

import json
import uuid
import re

MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017
client = MongoClient(MONGODB_HOST, MONGODB_PORT)
db = client['laddu']
GRAPH_DB = db['ladduGraphData']


STATUS_CHOICES = (
	(1, 'Success'),
	(2, 'Failed'),
)

RUNNING_STATUS_CHOICES = (
	(True, "Running"),
	(False, "Paused"),
	(None, "Stopped"),
)

PROTOCOL_CHOICES = (
	('http://', 'http://'),
	('https://', 'https://'),
)

FREQUENCY_CHOICES = (
	(15,'15 Minutes'),
	(30,'30 Minutes'),
	(60,'1 Hour'),
	(120,'2 Hour'),
	(720, '12 Hour'),
	(1440,'Day(01:00 IST)'),
)


class ActiveObjects(models.Manager):
    def get_queryset(self):
        return super(ActiveObjects, self).get_queryset().filter(active=True).order_by('-id')




class Wallet(models.Model):
	owner = models.ForeignKey(User)
	smsCredits = models.PositiveIntegerField( default = 10 )
	
	active = models.BooleanField(default=True)
	addedOn = models.DateTimeField(auto_now_add=True, default=datetime.now)
	UpdatedOn = models.DateTimeField(auto_now=True, default=datetime.now)
	
	objects = models.Manager()
	activeObjects = ActiveObjects()
	
	
	
	
	
	
class Laddu(models.Model):
	owner = models.ForeignKey(User)
	protocol = models.CharField(choices=PROTOCOL_CHOICES, max_length=10, default='http://')
	url = models.TextField()
	slug = models.SlugField(null=True, blank=True)
	
	frequency = models.PositiveIntegerField(choices = FREQUENCY_CHOICES, default=120)
	runningStatus = models.NullBooleanField(choices=RUNNING_STATUS_CHOICES, default=True)
	
	active = models.BooleanField(default=True)
	addedOn = models.DateTimeField(auto_now_add=True, default=datetime.now)
	UpdatedOn = models.DateTimeField(auto_now=True, default=datetime.now)
	
	objects = models.Manager()
	activeObjects = ActiveObjects()
	
	def getSlug(self):
		return self.slug if self.slug else self.id
	
	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(str(uuid.uuid4().get_hex().upper()[0:6]) + '-' + re.sub(r'[^\w]', ' ', self.url[:20]))
		super(Laddu, self).save(*args, **kwargs)
	
	
	
	#def __unicode__(self):
		#return unicode(self.url)[:50] + ' ' + str(self.frequency) + 'm'
		
	def isActiveSmsAlert(self):
		return True if SmsAlert.activeObjects.filter(laddu=self).exists() else False
	
	def isActiveEmailAlert(self):
		return True if EmailAlert.activeObjects.filter(laddu=self).exists() else False
	
	def activeAlerts(self):
		alerts  = []
		if self.isActiveEmailAlert():
			alerts.append('sms')
		if self.isActiveEmailAlert():
			alerts.append('email')
		return alerts
	
	def getSMSAlertNumbers(self):
		return SmsAlert.activeObjects.filter(laddu=self)
	
	def getEMAlertNumbers(self):
		return EmailAlert.activeObjects.filter(laddu=self)
	
	def doAlert(self,statusCode,statusReason):
		alerts = self.activeAlerts()
		
		# send sms
		for smsToSend in self.getSMSAlertNumbers():
			if not self.updateWalletSMS():
				break
			
			message = "!!!Website DOWN :"
			message += self.url[:20]
			message += " Status:"
			message += str(statusCode) if statusCode else "NOT OK"
			message += (' (' + str(statusReason) + ')')  if statusCode else ""
			print "sending sms to " + smsToSend.number + ' : ' + message 
			sendSMS.delay(smsToSend.number,message)
		
		# send emails
		emailTos = [ x.email for x in self.getEMAlertNumbers() ]
		subject = "WebSite Down : " + self.protocol + self.url
		message = "Last check for your web site " + self.protocol + self.url + " failed <br>"
		message += "for more details please login to your chick ping dashboard"
		sendEmail.delay( emailTos, subject, message)
	
	def updateWalletSMS(self,debit=1):
		w, created = Wallet.activeObjects.get_or_create(owner = self.owner)
		if w.smsCredits:
			w.smsCredits = w.smsCredits-debit
			w.save()
			return True
		else :
			return False
		
	def saveStatus(self,status, reason, responceTime):
		try:
			status = int(status)
		except:
			status = None
			if not reason:
				reason = "Unknown Status"
		ls = LadduStatus(laddu=self, status=status, statusReason=reason, responceTimeSeconds = responceTime)
		ls.save()
		#print reason
		if reason == "('Connection aborted.', gaierror(-2, 'Name or service not known'))":
			reason = "Name or service not known"
			
		gElement = [{
			'x' : (int(time.time()))*1000,
			'y' : responceTime if responceTime else 0,
			'testStatus' : {
				'code' : status if status else 'Unknown',
				'reason' : reason,
				}
			},]
		if not GRAPH_DB.find({'laddu':self.id}).count():
			GRAPH_DB.insert({'laddu':self.id, 'graph':gElement})
		else:
			gElement = GRAPH_DB.find_one({'laddu':self.id})['graph'] + gElement
			GRAPH_DB.update({'laddu':self.id},{"$set":{'graph':gElement}})
			
		ls, created = LadduStatics.objects.get_or_create(laddu = self)
		
		### ALERT
		if ( not status ) or ( status in range(400,600) ):
			self.doAlert(status, reason)
			ls.failCount = 1 if not ls.failCount else (ls.failCount + 1)
		else:
			ls.successCount = 1 if not ls.successCount else (ls.successCount + 1)
		ls.save()
	
	def getGraph(self):
		if GRAPH_DB.find({'laddu':self.id}).count():
			gElement = GRAPH_DB.find_one({'laddu':self.id})['graph']
			return gElement
		else:
			return None
	
	def getSuccessCount(self):
		ls = None
		try : 
			ls = LadduStatics.objects.get(laddu = self)
		except:
			pass
		return ls.successCount if ls and ls.successCount else 0
	
	def getFailCount(self):
		ls = None
		try : 
			ls = LadduStatics.objects.get(laddu = self)
		except:
			pass
		return ls.failCount if ls and ls.failCount else 0


class LadduStatus(models.Model):
	laddu = models.ForeignKey(Laddu)
	
	status = models.PositiveSmallIntegerField(null=True,blank=True)
	statusReason = models.TextField(null=True, blank=True)
	responceTimeSeconds = models.FloatField(null=True, blank=True)
	
	active = models.BooleanField(default=True)
	addedOn = models.DateTimeField(auto_now_add=True)
	UpdatedOn = models.DateTimeField(auto_now=True)


class SmsAlert(models.Model):
	laddu = models.ForeignKey(Laddu)
	number = models.TextField()
	
	active = models.BooleanField(default=True)
	addedOn = models.DateTimeField(auto_now_add=True)
	UpdatedOn = models.DateTimeField(auto_now=True)
	
	objects = models.Manager()
	activeObjects = ActiveObjects()
	

class EmailAlert(models.Model):
	laddu = models.ForeignKey(Laddu)
	email = models.TextField()
	
	active = models.BooleanField(default=True)
	addedOn = models.DateTimeField(auto_now_add=True)
	UpdatedOn = models.DateTimeField(auto_now=True)
	
	objects = models.Manager()
	activeObjects = ActiveObjects()

class LadduStatics(models.Model):
	laddu = models.ForeignKey(Laddu, primary_key=True)
	successCount = models.PositiveSmallIntegerField(null=True,blank=True)
	failCount = models.PositiveSmallIntegerField(null=True,blank=True)	
	def getSuccessPercent(self):
		return ( self.successCount / ( self.successCount + self.failCount ) ) * 100


class UserStatics(models.Model):
	user = models.ForeignKey(User, primary_key=True)
	def getRunningJobsCount(self):
		return Laddu.objects.filter(runningStatus=True).count()

class UserForm(ModelForm):
	class Meta:
		model = User
		fields = ('username', 'email', 'password')
		
class Secretkey(models.Model):
	username = models.CharField(max_length=40)
	key = models.CharField(max_length=20)
	active = models.BooleanField(default=True)
	

from datetime import timedelta
class userExtension:
	user = None
	laddus = None
	
	def __init__(self,u):
		self.user = u
		self.laddus = Laddu.activeObjects.filter(owner = self.user)
		
	def runningJobCount(self):
		return self.laddus.count()
	
	def weekJobCount(self):
		
		date = datetime.today()
		start_week = date - timedelta(date.weekday())
		end_week = start_week + timedelta(7)
		return LadduStatus.objects.filter(laddu__in= self.laddus, UpdatedOn__range=[start_week, end_week]).count()
	
	def failedChecks(self):
		date = datetime.today()
		start_week = date - timedelta(date.weekday())
		end_week = start_week + timedelta(7)
		fLcount = LadduStatus.objects.filter(laddu__in= self.laddus, UpdatedOn__range=[start_week, end_week], status__range=[400,600]).count()
		fLcount += LadduStatus.objects.filter(laddu__in= self.laddus, UpdatedOn__range=[start_week, end_week], status=None ).count()
		return fLcount
	
	def smsCreditsRemaing(self):
		w, created = Wallet.activeObjects.get_or_create(owner = self.user)
		return w.smsCredits

templates/502.html
<!--Code for 502 error message-->
<html>
	<head>
		<title></title>
		<meta content="">
		<link href='//fonts.googleapis.com/css?family=Asap:400,700' rel='stylesheet' type='text/css'>

		<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
		<style>
			body{
				background:#D0E0EB;
			}
			h2 h1{
				font-family: 'Asap', cursive;
				margin: auto;
				display: block;
				text-align: center;
			}
			img{
				display: block;
				margin:auto;
				margin-top: 200px;
				width:300px;
				height:300px;
			}
			.container{
				width:100%;
				height:auto;
				margin: auto;

			}
			h1{
				font-size:12em;
			}
			h2{
				font-style:italic;
				color:grey;
			}
		</style>
	</head>
	<body >
		<div class="container">
			<center><h1> Oops! 502 </h1></center>
			<center> <h2>Server maintenance in progress.</h2></center>
		</div>
	</body>
</html>

templates/Home.html
{% extends "base.html" %}

{% block content %}


<div class="page-header">
	<div class="page-title">
		<h3>Dashboard</h3>
	</div>
</div>

<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<ul class="info-blocks">
			
			<li class="bg-primary">
				<a class="info-Number" href="{% url 'jobs'%}">{{userExtn.runningJobCount|default:"0"}}</a>
				<span class="bottom-info bg-danger">Running Jobs</span>
			</li>
			
			<li class="bg-success">

				<a class="info-Number" href="{% url 'jobs'%}">{{userExtn.weekJobCount|default:"0"}}</a>
				<span class="bottom-info bg-primary">Checks in Last 24Hrs</span>
			</li>
			
		</ul>
		<ul class="info-blocks">
			
			<li class="bg-danger">

				<a class="info-Number" href="{% url 'jobs'%}">{{userExtn.failedChecks|default:"0"}}</a>
				<span class="bottom-info bg-primary">Failed Checks</span>
			</li>
			
			<li class="bg-info">

				<a class="info-Number" href="{% url 'jobs'%}">{{userExtn.smsCreditsRemaing|default:"0"}}</a>
				<span class="bottom-info bg-primary">SMS Alets Remaining</span>
			</li>
		</ul>
	</div>

</div>
<!-- /table hover -->




{% endblock %}                

templates/JobStatus.html
{% extends "base.html" %}
{% load jsonify %}
{% block content %}
{% load poll_extras %}
<script src="{{STATIC_URL}}highcharts/highcharts.js"></script>
<script src="{{STATIC_URL}}highcharts/data.js"></script>
<script src="{{STATIC_URL}}highcharts/heatmap.js"></script>
<script src="{{STATIC_URL}}highcharts/exporting.js"></script>

<script src="{{STATIC_URL}}jquery.inputmask.js" type="text/javascript"></script>
<script src="{{STATIC_URL}}jquery.inputmask.date.extensions.js" type="text/javascript"></script>
<script src="{{STATIC_URL}}jquery.inputmask.extensions.js" type="text/javascript"></script>
<script src="{{STATIC_URL}}jobStatusGraph.js" type="text/javascript"></script>
<script src="{{STATIC_URL}}jobActions.js" type="text/javascript"></script>





<div class="page-header">
	<div class="page-title">
		<h3><i class="icon-stats"></i>Job Status</h3>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<h3 class=""><i class="icon-link"></i> <samp>{{laddu.protocol}}{{laddu.url}}</samp></h3>
	</div>

</div>
<div class="row {{laddu.runningStatus|yesno:"running,stopped"}} jobRow">
	<div class="col-md-5 col-md-offset-1">

		<span> Check Status :</span> <span class="status status-success runningShow"></span><span class="status status-warning stoppedShow"></span> <small class="runningShow">Running</small><small class="stoppedShow">Stopped</small>
		<br>
		<span>Checking Every {{laddu.get_frequency_display}}</span>
		<hr>
	</div>
	<div class="col-md-5 jobactions" style="text-align: right;">



		<a href="{% url 'jobStop' laddu.getSlug %}" class="jobStop btn  runningShow"><i class="icon-pause2"></i> Pause</a>

		<a href="{% url 'jobStart' laddu.getSlug %}" class="jobStart btn  stoppedShow"><i class="icon-play3"></i> Continue</a>


		<a href="{% url 'jobRemove' laddu.getSlug %}" class="jobRemove btn "><i class="icon-remove"></i> Remove</a>
		<!--<a href="#" class="btn btn-link btn-icon btn-xs"><i class="icon-camera5"></i></a>-->

		<hr>
	</div>
</div>	
<div class="row">
	<div class="col-md-12">

		<div class="panel panel-default">
			<div class="panel-heading">
				<h6 class="panel-title"><i class="icon-stats"></i> Status Response Time</h6>
			</div>
			<div class="panel-body">
				<div id='gContainer' style="width: 98%"></div>
			</div>
		</div>

	</div>
</div>
<div class="row">
	<div class="col-md-12">


		<div class="panel panel-default">
			<div class="panel-heading">
				<h6 class="panel-title">
					<i class="icon-phone"></i> SMS Alerts
				</h6>

			</div>
			<div class="panel-body">

				<div class="block-inner text-info">
					<small class="display-block">Alerts you when the the check is a failure, Eg : when response code is in between 400 and 600</small>
				</div>
				<div class="block-inner text-info sbHeading">
					<h6 class="heading-hr">Enabled phone numbers</h6>
				</div>

				<ul class="message-list smsList">
					{% for sAl in laddu.getSMSAlertNumbers %}
					<li class="noPaddding smsLi" >

						<div class="clearfix">

							<div class="chat-member">
								<h6><i class="icon-phone"></i>{{sAl.number}}</h6>
							</div>

							<div class="chat-actions">
								<a href="{% url 'delSMSAlert' laddu.getSlug sAl.number %}" class="jobRemove btn btn-link btn-icon btn-xs"><i class="icon-remove"></i></a>
								<!--<a href="#" class="btn btn-link btn-icon btn-xs"><i class="icon-camera5"></i></a>-->
							</div>
						</div>

					</li>
					{% endfor %}
					<li class="noPaddding emptyMsg" >
						<div class="clearfix">
							<div class="chat-member text-warning">
								<h6><i class="icon-warning"></i> No phone numbers to send SMS alerts.</h6>
							</div>

						</div>
					</li>

				</ul>

				<div class="block-inner text-danger" style="margin-top: 64px;">
					<h6 class="heading-hr" id="toggleAddSMSform"><i class="icon-plus " ></i> Add Phone Number</h6>
				</div>
				<form action="{% url 'addSMSAlert' laddu.getSlug %}" role="form" id="addSMSform" style="display: none">
					<div class="form-group">
						<div class="row">
							<div class="col-md-6">
								<label>Phone :</label>
								<input required="" name="number" type="text" class="form-control mobile">
								<span class="help-block">+99-99-9999-9999</span>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<input type="submit" value="Add" class="btn btn-success pull-right">
						</div>
					</div>
				</form>
			</div>
		</div>

	</div>
</div>


<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h6 class="panel-title">
					<i class="icon-mail3"></i> E-Mail Alerts
				</h6>

			</div>
			<div class="panel-body">

				<div class="block-inner text-info">
					<small class="display-block">Alerts you when the the check is a failure, Eg : when response code is in between 400 and 600</small>
				</div>
				<div class="block-inner text-info sbHeading">
					<h6 class="heading-hr">Enabled email addresses</h6>
				</div>

				<ul class="message-list smsList">
					{% for eAl in laddu.getEMAlertNumbers %}
					<li class="noPaddding smsLi" >

						<div class="clearfix">

							<div class="chat-member">
								<h6><i class="icon-mail3"></i>{{eAl.email}}</h6>
							</div>

							<div class="chat-actions">
								<a href="{% url 'delEMAlert' laddu.getSlug eAl.email %}" class="jobRemove btn btn-link btn-icon btn-xs"><i class="icon-remove"></i></a>
								<!--<a href="#" class="btn btn-link btn-icon btn-xs"><i class="icon-camera5"></i></a>-->
							</div>
						</div>

					</li>
					{% endfor %}
					<li class="noPaddding emptyMsg" >
						<div class="clearfix">
							<div class="chat-member text-warning">
								<h6><i class="icon-warning"></i> No E-mail address to send alerts.</h6>
							</div>

						</div>
					</li>

				</ul>

				<div class="block-inner text-danger" style="margin-top: 64px;">
					<h6 class="heading-hr" id="toggleAddEMform"><i class="icon-plus "  ></i> Add E-mail Address </h6>
				</div>
				<form action="{% url 'addEMAlert' laddu.getSlug %}" role="form" style="display: none" id="addEMform">
					<div class="form-group">
						<div class="row">
							<div class="col-md-6">
								<label>Email :</label>
								<input required="" name="email" type="email" class="form-control ">

							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<input type="submit" value="Add" class="btn btn-success pull-right">
						</div>
					</div>
				</form>
			</div>
		</div>

	</div>
</div>








<script>

	var color = ["#7cb5ec", "#ff3c50"]
	var p = {{laddu.getGraph | jsonify}};
	graphify_FULL('#gContainer', p, '{{laddu.protocol}}{{laddu.url|truncatechars:20}}', {{laddu.getSuccessCount}}, {{laddu.getFailCount}});
	$('.mobile').inputmask("009{5,16}");
	$('.email').inputmask("email");
	$('#toggleAddEMform').click(function(){
$('#addEMform').slideDown(500)
	})
	$('#toggleAddSMSform').click(function(){
$('#addSMSform').slideDown(500)
	})
</script>





{% endblock %}                

templates/Jobs.html
{% extends "base.html" %}
{% load jsonify %}
{% block content %}
{% load poll_extras %}
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/data.js"></script>
<script src="http://code.highcharts.com/modules/heatmap.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<script src="{{STATIC_URL}}jobsgraph.js" type="text/javascript"></script>
<script src="{{STATIC_URL}}jobActions.js" type="text/javascript"></script>

<style>
	.highcharts-tooltip>span {
		background: rgba(255,255,255,0.85);
		border: 1px solid silver;
		border-radius: 3px;
		box-shadow: 1px 1px 2px #888;
		padding: 8px;
		z-index: 2;
	}
	.chatChart
	{
		float: left;
		/*width: 30%;*/
	}
	.chat-member
	{
		/*max-width: 40%;*/
		margin-top: 10px;
	}
	.chat-actions
	{
		/*width: 30%;*/
		text-align: right;
		margin-top: 10px;
	}
	.message-list > li.noPaddding
	{
		padding: 0 0 0 0;
	}
</style>





<div class="page-header">
	<div class="page-title">
		<h3>Monitor Jobs</h3>
	</div>
</div>

<div class="panel panel-default">
		<!--<div class="panel-heading"><h6 class="panel-title"><i class="icon-bubble4"></i> Form elements</h6></div>-->
		<div class="panel-body">

		<ul class="message-list jobList">{% for l in laddus %}
			<li class="noPaddding jobLi" >

				<div class="clearfix row {{l.runningStatus|yesno:"running,stopped"}} jobRow">

					<div class="chat-member col-md-8">
						<a href="{% url 'jobStats' l.getSlug %}">
							<h6>{{l.protocol}}{{l.url}}<span class="status status-success runningShow"></span><span class="status status-warning stoppedShow"></span> <small class="runningShow">Running</small><small class="stoppedShow">Stopped</small> <small> Every {{l.get_frequency_display}}</small></h6>
						</a>
					</div>
					<!--<div class="chatChart col-md-6"><div id="container{{l.id}}" style="height: 60px; width: 100%; margin: 0 auto"></div></div>-->

					<div class="chat-actions col-md-4  jobactions" style="text-align: right;">
						<a href="{% url 'jobStats' l.getSlug %}" class="btn btn-link btn-icon btn-xs"><i class="icon-stats"></i></a>
						<!--<a href="#" class="btn btn-link btn-icon btn-xs"><i class="icon-settings"></i></a>-->


						<a href="{% url 'jobStop' l.getSlug %}" class="jobStop btn btn-link btn-icon btn-xs runningShow"><i class="icon-pause2"></i></a>

						<a href="{% url 'jobStart' l.getSlug %}" class="jobStart btn btn-link btn-icon btn-xs stoppedShow"><i class="icon-play3"></i></a>


						<a href="{% url 'jobRemove' l.getSlug %}" class="jobRemove btn btn-link btn-icon btn-xs"><i class="icon-remove"></i></a>
						<!--<a href="#" class="btn btn-link btn-icon btn-xs"><i class="icon-camera5"></i></a>-->
					</div>
				</div>

			</li>
			{% endfor %}
			<li class="noPaddding jobLi jobLiEmpty" >

				<div class="clearfix row {{l.runningStatus|yesno:"running,stopped"}} jobRow">

					<div class="chat-member col-md-12">
						<a href="{% url 'newJob' %}">
							<h6 class="text-warning">Oops! Give use some thing to monitor, You can add your web site here</h6>
						</a>
					</div>
				</div>

			</li>
		</ul>



	</div>
</div>



{% for l in laddus %}

<script>
//	graphify('#container{{l.id}}', {{l.getGraph | jsonify}}, '{{l.protocol}}{{l.url|truncatechars:20}}');
</script>
{% endfor %}




{% endblock %}                

templates/resetPassword.html
{% extends "base.html" %}

{% block content %}

<form role="form" action="{% url 'resetPasswordSave' %}"  method="post">{% csrf_token %}
	<div class="panel panel-default" style="width: 624px; margin-left: 195px; margin-top: 50px;">

		<div class="panel-heading"><h6 class="panel-title"><i class=""></i>Reset password</h6></div>
		<div class="panel-body">
			{% if success %}
			<div class="alert alert-warning fade in block success_msg">
				<button type="button" class="close close_success">×</button>
				<i class="icon-info"></i> Your Password reseted successfully...
			</div>
			{% endif %}
			<div class="form-group">
				<label>Password</label>
				<input type="password" class="form-control required password" required placeholder="Password" name='password1'>
			</div>
			<div class="form-group">
				<label>Confirm password</label>
				<input type="password" class="form-control required password" required placeholder="Password" name='password2'>
			</div>
			{% if password_incorrect %}
			<div class="alert alert-warning fade in block  password_no_mach">
				<button type="button" class="close close_nomatch">×</button>
				<i class="icon-info"></i> Your new password is incorrect , Please try again.
			</div>
			{% endif %}
			<div class="form-actions text-right">
				<button type="submit" class="btn btn-primary">Reset</button>
			</div>

		</div>


	</div>

</form>

<script>
	$(".close_nomatch").click(function()
	{
		$(".password_no_mach").hide()
	})
	$(".close_success").click(function()
	{
		$(".success_msg").hide()
	})

</script>
{% endblock%}